### ISSUE TITLE
Adicionar um texto de copyright em cada componente - Juggernaut demo

### ISSUE THREAD

**Issue by stanleygomes** [stanleygomes/hacktoberfest-2021#6]
Nesse projeto na página inicial onde tem a lista de componentes, no final da página tem um texto:

*Copyright © Softbox. Built with by Juggernaut.*

Pegar esse mesmo texto e colocar no final da página de cada componente.

PS.: Tem um PR de mudar o nome Softbox para Luizalabs, pode deixar softbox aqui, para que seja alterado no outro PR.

Pode visualizar o projeto aqui:
https://juggernaut-demo.web.app

Repositório para o PR é:
https://github.com/luizalabs/juggernaut-demo

**Comment by PabloAlves** [comment]
Feito na branch pabloalves/add_copyright_components.
